<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">
*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<!--NAVIGATION-->
< [Data Manipulation with Pandas](03.00-Introduction-to-Pandas.ipynb) | [Contents](Index.ipynb) | [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb) >

# 3.2 Introducing Pandas Objects / Pandas 对象简介

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.
As we will see during the course of this chapter, Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

We will start our code sessions with the standard NumPy and Pandas imports:

In [52]:
# 🐍 import Numpy和Pandas库

import numpy as np
import pandas as pd

## 3.2.1 The Pandas Series Object / Pandas 的 Series 对象

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [55]:
# 🐍 Series 是一个带索引的一维数组

data = pd.Series([0.25, 0.5, 0.75, 1.0])
type(data)
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [79]:
data.values.mean()

# type(data.values)

0.625

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [57]:
data.index

type(data.index)

pandas.core.indexes.range.RangeIndex

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [59]:
data[2]

0.75

In [60]:
data[1:3]

1    0.50
2    0.75
dtype: float64

As we will see, though, the Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy array that it emulates.

### 1. Series as generalized NumPy array / Series 是通用的 NumPy 数组

From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
The essential difference is the presence of the index: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an *explicitly defined* index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.
For example, if we wish, we can use strings as an index:

In [61]:
# 🐍 Numpy数组通过隐式定义的整数索引获取数值
# 🐍 Panadas的Series对象用显式定义的索引与数值关联
# 🐍 Series的索引不再仅仅是整数，可以是任意想要的类型

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 0.75, 'd'])
data

a       0.25
b       0.50
0.75    0.75
d       1.00
dtype: float64

And the item access works as expected:

In [63]:
data[0.75]

0.75

We can even use non-contiguous or non-sequential indices:

In [64]:
# 🐍 Series索引可以使用不连续或不按顺序的索引

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [65]:
data[5]

0.5

### 2. Series as specialized dictionary / Series 是特殊的字典

In this way, you can think of a Pandas ``Series`` a bit like a specialization of a Python dictionary.
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps typed keys to a set of typed values.
This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [66]:
# 🐍 可以把Pandas的Series对象看成一种特殊的Python字典
# 🐍 字典是一种将任意键映射到一组任意值的数据结构
# 🐍 Series对象其实是一种将类型键映射到一组类型值得数据结构

In [15]:
# 🐍 字典population_dict
# 🐍 Series对象population
# 🐍 字典创建Series对象时，其索引默认按照顺序排列

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

By default, a ``Series`` will be created where the index is drawn from the sorted keys.
From here, typical dictionary-style item access can be performed:

In [67]:
# 🐍 字典数值获取方式对Series对象仍然有效

population['California']

38332521

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [68]:
# 🐍 Series对象还支持数组形式得操作，如切片

population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

We'll discuss some of the quirks of Pandas indexing and slicing in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### 3. Constructing Series objects / 创建 Series 对象

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [70]:
# 🐍 创建Pandas的Series对象，形式：pd.Series(data, index=index)
# 🐍 data可以是列表，字典，NumPy数组，index可选，默认值为整数序列

pd.Series([2, 4, 6], index=['x', 'y','z'])

x    2
y    4
z    6
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [72]:
pd.Series('xyz', index=[100, 200, 300])

100    xyz
200    xyz
300    xyz
dtype: object

``data`` can be a dictionary, in which ``index`` defaults to the sorted dictionary keys:

In [20]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In each case, the index can be explicitly set if a different result is preferred:

In [74]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[2, 1, 3])

2    a
1    b
3    c
dtype: object

Notice that in this case, the ``Series`` is populated only with the explicitly identified keys.

## 3.2.2 The Pandas DataFrame Object / Pandas 的 DataFrame 对象

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
We'll now take a look at each of these perspectives.

### 1. DataFrame as a generalized NumPy array / DataFrame 是通用的 NumPy 数组
If a ``Series`` is an analog of a one-dimensional array with flexible indices, a ``DataFrame`` is an analog of a two-dimensional array with both flexible row indices and flexible column names.
Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
Here, by "aligned" we mean that they share the same index.

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

In [80]:
# 🐍 DataFrame可以看作一种既有行索引，又有列索引的二维数组

In [81]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [24]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [82]:
# 🐍 DataFrame的index属性

states.index

type(states.index)

pandas.core.indexes.base.Index

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [84]:
# 🐍 DataFrame的columns属性

states.columns

type(states.columns)

pandas.core.indexes.base.Index

Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

### 2. DataFrame as specialized dictionary / DataFrame 是特殊的字典

Similarly, we can also think of a ``DataFrame`` as a specialization of a dictionary.
Where a dictionary maps a key to a value, a ``DataFrame`` maps a column name to a ``Series`` of column data.
For example, asking for the ``'area'`` attribute returns the ``Series`` object containing the areas we saw earlier:

In [27]:
# 🐍 可以把DataFrame看成一种特殊的字典
# 🐍 字典是一种将任意键映射到一组任意值的数据结构
# 🐍 DataFrame是一个列映射一个Series对象的数据

In [85]:
# 🐍 DataFrame 是一列映射一个 Series 的数据。例如，通过'area'的列属性可以返回包含面积数据的Series对象：

states['area']

type(states['area'])

pandas.core.series.Series

Notice the potential point of confusion here: in a two-dimesnional NumPy array, ``data[0]`` will return the first *row*. For a ``DataFrame``, ``data['col0']`` will return the first *column*.
Because of this, it is probably better to think about ``DataFrame``s as generalized dictionaries rather than generalized arrays, though both ways of looking at the situation can be useful.
We'll explore more flexible means of indexing ``DataFrame``s in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### 3. Constructing DataFrame objects / 创建 DataFrame 对象

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### (1) From a single Series object / 通过单个 Series 对象创建

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

In [88]:
# 🐍 通过单个Series 对象创建。单个Series创建一个单列的DataFrame

df_population = pd.DataFrame(population, columns=['population'])

print(df_population, population, sep='\n\n')

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

#### (2) From a list of dicts / 通过字典列表创建

Any list of dictionaries can be made into a ``DataFrame``.
We'll use a simple list comprehension to create some data:

In [89]:
# 🐍 通过字典列表创建。任何元素是字典的列表都可以变成 DataFrame

data = [{'a': i, 'b': 2 ** i}
        for i in range(10)]
pd.DataFrame(data)

   a    b
0  0    1
1  1    2
2  2    4
3  3    8
4  4   16
5  5   32
6  6   64
7  7  128
8  8  256
9  9  512

Even if some keys in the dictionary are missing, Pandas will fill them in with ``NaN`` (i.e., "not a number") values:

In [34]:
# 🐍 字典中有些键不存在，Pandas 会用缺失值NaN（不是数字，not a number）来表示

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### (3) From a dictionary of Series objects / 通过 Series 对象字典创建

As we saw before, a ``DataFrame`` can be constructed from a dictionary of ``Series`` objects as well:

In [38]:
# 🐍 通过Series对象字典创建

print(population, type(population), sep='\n')
print(area, type(area), sep='\n')

pd.DataFrame({'population': population,
              'area': area})

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
<class 'pandas.core.series.Series'>
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64
<class 'pandas.core.series.Series'>

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### (4) From a two-dimensional NumPy array / 通过 Numpy 二维数组创建

Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
If omitted, an integer index will be used for each:

In [39]:
# 🐍 通过NumPy二维数组创建

pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.248719  0.491785
b  0.480347  0.361953
c  0.511404  0.933681

#### (5) From a NumPy structured array / 通过 NumPy 结构化数组创建

We covered structured arrays in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).
A Pandas ``DataFrame`` operates much like a structured array, and can be created directly from one:

In [40]:
# 🐍 通过NumPy 结构化数组创建

A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [56]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

## 3.2.3 The Pandas Index Object / Pandas 的 Index 对象

We have seen here that both the ``Series`` and ``DataFrame`` objects contain an explicit *index* that lets you reference and modify data.
This ``Index`` object is an interesting structure in itself, and it can be thought of either as an *immutable array* or as an *ordered set* (technically a multi-set, as ``Index`` objects may contain repeated values).
Those views have some interesting consequences in the operations available on ``Index`` objects.
As a simple example, let's construct an ``Index`` from a list of integers:

In [98]:
# 🐍 Pandas的 Index 对象, 可以将它看作是一个不可变数组或有序集合

ind = pd.Index([2, 3, 'x', 7, 11])
ind

Index([2, 3, 'x', 7, 11], dtype='object')

### 1. Index as immutable array / 将 Index 看作不可变数组

The ``Index`` in many ways operates like an array.
For example, we can use standard Python indexing notation to retrieve values or slices:

In [100]:
type(ind[2])

str

In [43]:
ind[::2]

Index([2, 5, 11], dtype='int64')

``Index`` objects also have many of the attributes familiar from NumPy arrays:

In [44]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

One difference between ``Index`` objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [45]:
# 🐍 Index 对象与NumPy 数组之间的不同在于，Index 对象的索引是不可变的

ind[1] = 0

TypeError: Index does not support mutable operations

This immutability makes it safer to share indices between multiple ``DataFrame``s and arrays, without the potential for side effects from inadvertent index modification.

### (2) Index as ordered set / 将 Index 看作有序集合

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic.
The ``Index`` object follows many of the conventions used by Python's built-in ``set`` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:

In [51]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [50]:
indA & indB  # intersection-交集

Index([0, 3, 5, 7, 9], dtype='int64')

In [48]:
indA | indB  # union-并集

Index([3, 3, 5, 7, 11], dtype='int64')

In [49]:
indA ^ indB  # symmetric difference - 异或

Index([3, 0, 0, 0, 2], dtype='int64')

These operations may also be accessed via object methods, for example ``indA.intersection(indB)``.

<!--NAVIGATION-->
< [Data Manipulation with Pandas](03.00-Introduction-to-Pandas.ipynb) | [Contents](Index.ipynb) | [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb) >